# Generated by Django 5.0.4 on 2024-05-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting', max_length=255, verbose_name='name test1')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('parameters', models.CharField(blank=True, default='', max_length=255, verbose_name='parameters')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Setting',
                'ordering': ('name',),
            },
        ),
    ]
